spring:
#  config:
#    activate:
#      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://blink-dev.cdm8koc66tdc.ap-northeast-2.rds.amazonaws.com:3306/blink_dev?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: blink_dev
    password: blink2024!!

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

#  data:
#    redis:
#      host: dib-redis-ro.vttt4f.ng.0001.apn2.cache.amazonaws.com:6379
#      port: 6379

### OPEN API
open-api:
  kakao:
    base-url: 'https://dapi.kakao.com'
    data-type: json
    service-key: e27761bd5230a26d8bd5b4b11c0e549d
    header-prefix: 'KakaoAK '
    open-key-url: https://kauth.kakao.com

# jwt
jwt:
  secret: 6d4e339f9edbdb307a097b40ed97422fb50cb785a65ef714fca970e07fd1532c2e033a2e3644cbb8e2aa0c6a516e7a857521fa93f0eac31d6c8fd39eea779481

# s3
#cloud:
#  aws:
#    s3:
#      bucket: dib-file-bucket
#      url: https://dib-file-bucket.s3.ap-northeast-2.amazonaws.com/
#    stack.auto: false
#    region.static: ap-northeast-2
#    credentials:
#      accessKey: AKIAUBNFHWZBIX2OIJJS
#      secretKey: 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

# kakao auth
kakao:
  auth:
    jwt:
      iss: https://kauth.kakao.com
      aud: dfb20dcf41d536b7c531ddafd8dddd8a
